### ISSUE TITLE
[bug] Export devices CSV is broken if comment field contains double quotes

### ISSUE THREAD

**Issue by orgalinq** [jokob-sk/NetAlertX#808] opened 2024-09-26 18:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

the CSV file lacks a double citation (") at the end of field dev_Comments.This doesn't happen in every row, but in some.  When importing the CSV file into Excel, a new row is created with field dev_FirstComment as start.

### Expected Behavior

see above.

### Steps To Reproduce

3. run csv export

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment] 2024-09-26 23:35
Hi @orgalinq ,

Thansk for the report!

I can't seem to reproduce the issue (opening the CSV in LibreOffice works fine). Would it be possible to post the file here or if it contains sensitive data, send me the file in question to netalertx@gmail.com ? 

It's possible a value in one of the fields breaks the formatting which then causes issues in Excel.

**Comment by orgalinq** [comment] 2024-09-28 17:17
With the previous release, the CSV export went well. After the update to the latest release, I did change some icons. 
Attached is the csv file. I see a line-feed at the end of field dev_comments for a few lines.

[devices.csv](https://github.com/user-attachments/files/17175662/devices.csv)

**Comment by orgalinq** [comment] 2024-09-28 17:31
I now see that where a line feed is inserted, these are the lines where the icons have been changed. The svg-html for these rows is larger than before.

**Comment by jokob-sk** [comment] 2024-09-28 22:28
Hi @orgalinq ,

Thanks for the details. The issue is caused by the quotes `"` in the comments fields. You can remove them yourself or otherwise, this should be fixed in the next release. It would be great if you could test this. Can you please switch to the `netalertx-dev` docker image (backup everything at first), in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

Thanks in advance,
j


```yaml
sudo docker run --pull always --rm --network=host \
  -v /app/config:/app/config \
  -v /app/db:/app/db \
  -v /app/log:/app/log \
  -e TZ=America/New_York \
  -e PORT=20211 \
  jokobsk/netalertx-dev
```

**Comment by orgalinq** [comment] 2024-09-29 10:41
Hi jokob-sk,

Do you think I've entered field quotes in the dev_Comments and that's why the rows are broken? 
I have just removed, as a precaution, all quotes in all text in dev_Comments. I even removed the quotes in all the fields. 
So I don't think that can be the cause. Rather, I think the cause lies in the (large) length of the field dev_Icon. I notice that these are the rows where I have changed the icons, which has made the length of the field dev_Icon (possible too) large. 
Of course I would like to test with the Dev_image, if you want me to do.

what do you think

**Comment by jokob-sk** [comment] 2024-09-29 12:07
Hi @orgalinq, 

I think it's the quotes, but it would be better if you could test this - that's the only way how we can make sure it's fixed 

Thanks,
j

**Comment by orgalinq** [comment] 2024-09-29 16:53
Hi Jacob,
I'm familiar with updating a release with Portainer and using recreate.
It's very simple. I downloaded jokobsk/netalertx-dev using that procedure.
The download works, but the recreate doesn't. This gives an error in
Portainer.

I don't know (yet) how to install the developer release with your
procedure.

sudo docker run --pull always --rm --network=host
-v /app/config:/app/config
  -v /app/db:/app/db
  -v /app/log:/app/log
  -e TZ=America/New_York
  -e PORT=20211
  jokobsk/netalertx-dev

Can you help?

*  OrgaLinQ*


kokkelmanlanden 23
7542 JC  Enschede
+31(0)651 608 840




Op zo 29 sep 2024 om 00:28 schreef jokob-sk ***@***.***>:

**Comment by jokob-sk** [comment] 2024-09-29 21:44
Hi @orgalinq ,

You should be able to set up a separate instance of NetAlertX (dev) running alongside the current setup. I haven't used the POrtainer way of settings things up, but I think this should work. 

I would recommend to the following:

1. Create a separate folder for the dev branch, let's call it `netalertx_dev` with folders `config` and `db`
2. Copy over the content from your current folders
3. Set up a separate app with the `netalertx-dev` image via Portainer pointing to these new folders.
4. Change the `PORT` ENV variable to e.g. `22222` 
5. Start the application and navigate to `<server IP>:22222`

These steps should allow you to run 2 separate NETALERTX instances, one on the production, and one on the dev image.

**Comment by orgalinq** [comment] 2024-09-29 23:37
Hi Jacob,

I created a new image jacob/netalertx_dev using portainer and did the test.
The results ,unfortunately, are the same as with your lastest release. See attachment.

[devices (3).csv](https://github.com/user-attachments/files/17181759/devices.3.csv)

**Comment by jokob-sk** [comment] 2024-09-30 00:50
Hi @orgalinq ,

Thanks a lot for testing it. I can open the file fine in LibreOffice, so the export part should work now. 

I found a couple of more bugs - now related to new lines in comments, and the use of non-ASCII characters, that prevented the file from being imported correctly. 

Can you re-download the -dev image? I pushed fixed which should allow you to import the supplied file.

**Comment by orgalinq** [comment] 2024-09-30 09:11
Hi Jacob,

First of all, I first tested your findings with the first dev release, not the new one.
When I load the csv with libreoffice then everything is ok. But with Excel I get some split rows again. 
And when I look at the csv with Notepad++, I see line feeds in the splited rows in Excel. Apparently, Libreoffice corrects this. My conclusion: the csv is not good yet!

Illustration: Here's what I see with Notepad++ in the first row that is split:

"b8:27:eb:3f:9a:cc","Homebridge 793C 97E6_hap","House","Server Raspberry","Raspberry Pi Foundation","0","--","This server provides the Home Automation and connections to Apple home and Google homeLF

Thus with a line-feed at the end of the split. 
The next row then proceeds as follows:

","2024-09-24 23:05:30+02:00","2024-09-24 23:05:30+02:00","192.168.178.54","0","1","1","0","1","0","2024-09-24 23:05:35+02:00","1","0","0","0","0","--","Internet","PGkgY2xhc3M9ImZhYiBmYS1yYXNwYmVycnktcGkiPjwvaT4=","c168145c-2b38-4b28-bfdc-de17dae2c411","None","--","--"LF

Again with a line-feed at the end, but that's correct here.

### **And now it comes!**
Still testing with your first dev-release:
After this, I re-keyed the texts in the dev_comments field of the splited rows. After that, it turned out that the line feeds have disappeared!! The import with Excel also went ok.

After this, I tested with your last public release:
I re-keyed the texts in the dev_comments field of the splited rows. After that, it turned out that the line feeds have disappeared!! The import with Excel also went ok.

Conclusion: solved !!!
The cause? I still think that my replacement of the icons has to do with introducing this (quotes)-bug

**Closed** 2024-09-30 12:11 UTC
Labels: bug 🐛, next release/in dev image🚀
