### ISSUE TITLE
Table on devices page does not load. 

### ISSUE THREAD

**Issue by nathang21** [jokob-sk/NetAlertX#869] opened 2024-11-01 01:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

The /devices page it shows the # of devices, but the table does not load at all.

Note: This is a follow-up from
https://github.com/jokob-sk/NetAlertX/issues/848#issuecomment-2435196787

### Expected Behavior

The table to render with a list of devices, with hyperlinks for the device names/ip addresses (as was added in a recent release).

### Steps To Reproduce

1. Load app
2. Click My devices on side bar
3. Wait for page to load
4. My devices table is missing

### app.conf

```python
See email.
```

### docker-compose.yml

```python
services:
  netalertx:
    image: jokobsk/netalertx-dev:latest 
    pull_policy: always
    container_name: netalertx
    healthcheck:
      test: curl -f http://localhost:20211/ || exit 1
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 300s
    mem_limit: 2g
    shm_size: 2g
    cpu_shares: 768
    network_mode: host
    security_opt:
      - no-new-privileges:true
    restart: always # unless-stopped # no
    stop_grace_period: 2m
    logging:
      driver: json-file
      options:
        max-file: 3
        max-size: 100k
    volumes:
      - /volume2/docker/netalertx/config:/app/config   
      - /volume2/docker/netalertx/db:/app/db   
      - /volume2/docker/netalertx/logs:/app/front/log  
      - /volume2/docker/netalertx/config/resolv.conf:/etc/resolv.conf   # Enable Reverse DNS
    environment:
      - LOG_LEVEL='trace' # info #
      # Fix Permissions by following:
      # https://github.com/jokob-sk/NetAlertX/blob/main/docs/FILE_PERMISSIONS.md
      # https://amoklauf.ch/posts/synology/changeid/
      - PUID=1030 
      - PGID=100
      - HOST_USER_ID=1030
      - HOST_USER_GID=100
      - TZ=America/New_York
```

### What branch are you running?

Dev

### app.log

See email.

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment] 2024-11-01 08:54
Hi @nathang21 ,

can you please post the console log of your browser? Usually this is a JavaScript or data validation issue. 

Also, please try opening the page in an incognito window to make sure the cache is not an issue.

Thanks,
j

**Comment by nathang21** [comment] 2024-11-01 14:49
I'm not seeing any obvious errors, pasting screenshot since pasting console output messing up the formatting.

<img width="2108" alt="image" src="https://github.com/user-attachments/assets/eb04984c-215b-4c54-80bf-06acbd8bae14">

**Comment by jokob-sk** [comment] 2024-11-01 20:53
Hi @nathang21 ,

Thanks for that! Hummmm, yeah, no obvious errors. Also weird the menu doesn't render properly. 

Could you please try the following?

1. Try accessing the API endpoint for the devices: `http://<host>:<api>/api/table_devices.json`. It should return an array of objects representing devices. 
3. Could you confirm the same behavior happens in other browsers (Firefox, Edge, Chrome)?
4. Did you clear the browser cache (usually shift + refresh)? 
5. Could you try refreshing the app cache by clicking the reload button in the header (🔃)?
6. Are you by chance running a reverse proxy (I'm not testing it on one and sometimes reverse proxy setups break)? If so, can you try disabling it?
7. If you have some privacy plugins or enhanced browser protection levels, can you please try disabling those?

The good thing is the backend seems to run fine, it seems to be a front end issue. Judging by the number of devices and pages in the table. 


Thanks, 
j

**Comment by nathang21** [comment] 2024-11-04 00:01
Thanks @jokob-sk, menu issue I think was a weird glitch, I don't normally see it render that way, at least I can't reproduce it. 

1. Yes, I see a JSON array with 83 rows. 
2. Looks to happen in both Chrome + Firefox for Mac.
3. I have yes, as well as with a fresh browser. 
4. I tried this in both browsers, didn't help.
5. I am yes (NPM), although I did try bypassing the reverse proxy and the issue still occurs when accessing directly.
6. I tried in an environment without these and that didn't change anything. I do have a network wide ad/tracker blocker, but given this is open source software I don't expect that would be relevant here. 

Any other ideas? Looks like the correct data is indeed there, but for some reason is not being rendered.

**Comment by jokob-sk** [comment] 2024-11-04 02:21
Thanks for the answers! This is a stubborn one...

> 5. I am yes (NPM), although I did try bypassing the reverse proxy and the issue still occurs when accessing directly.

A. Can  you try temporarily disabling it as a test. Not sure if bypassing = same as disabling, but I would to make sure this is not the issue before exploring other things. 

---

> 6. I tried in an environment without these and that didn't change anything. I do have a network wide ad/tracker blocker, but given this is open source software I don't expect that would be relevant here.

B. I'm running AdGuard myself so I don't expect this to be an issue, but again, if possible, can you try to disable it and see if anything changes?

---
C. Can you have a look at `Integrations -> Plugins` (select a plugin with some entries) or `Monitoring -> Notifications` and make sure the table loads? I want to check if the issue is related to the dataTables plugin that is used in a few places. 

![image](https://github.com/user-attachments/assets/309be441-73f8-4b9d-af3a-d0b748cd1cb0)
---
D. As a sanity check - do you have columns that ought to be displayed in the table selected under `Settings -> UI_device_columns`?

**Comment by jokob-sk** [comment] 2024-11-17 11:21
no answer for over a week -> closing

**Closed by jokob-sk** 2024-11-17 11:21 UTC
Labels: bug 🐛, Waiting for reply⏳

**Comment by nathang21** [comment] 2024-11-22 02:27
Apologies for the delay, life got busy and kept forgetting to follow-up. 

--- 

A & B: Tried with no luck.

C: I confirmed other tables seems to load fine (integrations -> plugins & monitoring -> notifications). 

D: Wow I didn't even know this was a setting, I must have clicked "remove all" by accident at some point. I thought for sure this would have fixed it since it was empty, but even with changing that I Still get a blank table on the devices page. 

I'm still using the latest netalertx-dev image, let me know if you have further ideas, or want additional logs.

**Comment by jokob-sk** [comment] 2024-11-22 02:52
Hi @nathang21 ,

Thanks for the reply!

Since you said that D was empty I still suspect this to be the issue and now the cache might need to refresh. Could you please try:

 - re-save the settings 
 - opening the page in an incognito browser window
 - Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

**Comment by nathang21** [comment] 2024-11-22 03:15
Fantastic that did the trick, I could have sworn I tried that before posting my last reply, in any case, thanks for replying so quick!

**Comment by jokob-sk** [comment] 2024-11-22 04:03
Great to hear that :) glad this is resolved
