### ISSUE TITLE
Most showing as down

### ISSUE THREAD

**Issue by adm2k** [jokob-sk/NetAlertX#676] opened 2024-05-16 21:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

Why am I seeing this all of a sudden?
![image](https://github.com/jokob-sk/NetAlertX/assets/120423301/284ead4d-8125-4586-8f3f-42cb42998fc9)

In reality there are none down

### Expected Behavior

accurate reporting

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment] 2024-05-16 21:27
Hi there,

Please provide a screenshot of your enabled settings and the schedules you are using. They have to be in sync. Please check this for details https://github.com/jokob-sk/NetAlertX/blob/main/docs/NOTIFICATIONS.md

**Comment by adm2k** [comment] 2024-05-16 21:37
Hope this is what you need...
![image](https://github.com/jokob-sk/NetAlertX/assets/120423301/32ef2a56-275e-479a-a905-0941deb0069f)

**Comment by adm2k** [comment] 2024-05-16 21:46
Just checked again and it now shows this:
![image](https://github.com/jokob-sk/NetAlertX/assets/120423301/a3722e22-a786-47e2-8960-92121825d1d0)

Yet, the three shown as down are in fact not down.

thanks for looking at this...

**Comment by jokob-sk** [comment] 2024-05-16 21:52
It looks as the scans are working fine. Down & Offline combine offline and down devices. 29 devices - 26 online = 3 offline or down. The numbers seem right to me.

**Comment by adm2k** [comment] 2024-05-17 00:06
Just checked again at 9:15pm EST and it shows this. Even internet as down when it is not. Which I understood what is happening.
![image](https://github.com/jokob-sk/NetAlertX/assets/120423301/cf319286-f90d-44d7-8d68-59c9392bb84a)

**Comment by adm2k** [comment] 2024-05-17 10:19
Good morning,

Well still getting odd numbers on the display as shown in the previous comment from last night - still the same this morning. Devices showing down when they are in fact up. Might this have something to do with screen refreshes? I set it to refresh at 15 seconds just to see

Also, I am seeing devices with the same IP address but showing different MAC addresses see picture:
![image](https://github.com/jokob-sk/NetAlertX/assets/120423301/aa7a3c88-a89f-457b-8e21-3e50bd4049a0)

Really would like to get this working so I can depend on it.

Let me know what I can do if anything.

**Comment by jokob-sk** [comment] 2024-05-17 23:57
Hi there,

Could you please provide me with the app.log for the `ARPSCAN` plugin with **debug** enabled?

See these two guides for how to provide the details: 

https://github.com/jokob-sk/NetAlertX/blob/main/docs/DEBUG_TIPS.md
https://github.com/jokob-sk/NetAlertX/blob/main/docs/DEBUG_PLUGINS.md

You can also email sensitive data directly to jokob@duck.com

Please double-check you have debug enabled before sending or posting the logs as I will have to re-request the data if that's not the case.

**Comment by adm2k** [comment] 2024-05-18 00:31
@jokob-sk 

Sent log file to the email address you provided. Hope this is what you need...

thank again!

**Comment by jokob-sk** [comment] 2024-05-18 01:58
Thanks for the log.

1. Is the app also sending out incorrect notifications or is this only visible in the UI?
2. Can you please send me a screenshot of your Internet scan and Arp-scan settings?
3. How long does this incorrect state persist?
4. Could you please try to restart the container?

**Comment by adm2k** [comment] 2024-05-18 10:50
- Is the app also sending out incorrect notifications or is this only visible in the UI?
_**I have had notifications turned off while trying to get everything working. I did turn on for a short time and got some notifications for "disconnected" - these were for two cell phones and two Google nest speakers. The UI is where I see most of the concerns.**_
- Can you please send me a screenshot of your Internet scan and Arp-scan settings?
ARP-SCAN:
![image](https://github.com/jokob-sk/NetAlertX/assets/120423301/438ba5a7-1182-4d0a-8221-c5911f5eaec4)
Internet Check:
![image](https://github.com/jokob-sk/NetAlertX/assets/120423301/2bb551fc-0452-47da-ab1d-3dad62130ddd)
- How long does this incorrect state persist?
_**Can't seem to get a handle on that. I can view in browser and it is incorrect, clear cache and still incorrect. Close browser and check again after a few minutes and sometime it is correct and others incorrect. Seems to have a mind of its own. :)**_
- Could you please try to restart the container?
I have restarted the container many times and the VM at times also. Seems to make no difference. Here is the only way so far I have been able to get NetAlertX to run.
**_docker run -d --rm --network=host   -v "/$(pwd)/netalertx/config:/app/config"   -v "/$(pwd)/netalertx/db:/app/db"   -e TZ=America/New_York   -e PORT=20211   jokobsk/netalertx:latest_**

Sorry this is causing so much trouble, I hope we can get it resolved.
Al...

**Comment by jokob-sk** [comment] 2024-05-18 23:23
Hi @adm2k ,

Thanks for the details!

From the sounds of it, this is more of a UI issue than a notification-related one. Which is good as it's not that critical then.

The settings seem to be initialized to default values, so that shouldn't be the issue. 

1. Regarding the logs you sent me, are those during a period where incorrect data was shown? If it's not during a period when incorrect data in the UI was shown, could you please send me an app.log during such a period?
1. Are there any other errors, for example in the browser console, when this happens?

**Comment by adm2k** [comment] 2024-05-19 00:20
Greetings,

Well right now here is how things look: The number down is incorrect, most of these devices are online
![image](https://github.com/jokob-sk/NetAlertX/assets/120423301/6410fa54-8ff4-4ee2-8857-c6acf8c35f30)


No errors in the browser console.

There were several times today where I could not access anything in the setting sections. There were just "empty" bars being display - at this moment all is ok:
![image](https://github.com/jokob-sk/NetAlertX/assets/120423301/a2c3b2ca-cf47-42dc-a3f1-e27015a1652f)

I will send the current app log by email now. 

Also, I use the Homepage dashboard and the NetAlertx widget never seems to be correct and in particular never shows any values for "Down Alerts" see the first image above.
![image](https://github.com/jokob-sk/NetAlertX/assets/120423301/f307784b-c3fc-447c-9b52-1db965c3c7f9)

Thank you for your efforts on resolving this...
al

**Comment by jokob-sk** [comment] 2024-05-19 01:22
Hi @adm2k ,

> Well right now here is how things look: The number down is incorrect, most of these devices are online
> ![image](https://github.com/jokob-sk/NetAlertX/assets/120423301/6410fa54-8ff4-4ee2-8857-c6acf8c35f30)

I don't see an issue with the numbers: 30 devices - 24 connected = 6 down or offline - could you please clarify what's wrong in this screenshot?

If the above numbers are not correct can you provide me with an up-to-date screenshot where the numbers are incorrect?

I couldn't find anything unusual in the log file, but I may have also missed something since you send the whole log and not only for the time when the issue occurs. 

Regarding the Homepage dashboard widget - please contact the developer of the Homepage application as I'm not the author of the plugin. 

If you can provide me more detailed steps on how to reproduce the issue, I'll have a closer look, otherwise I'm unable to debug the issue further. 

In your original message you wrote:

> Expected Behavior
> 
> accurate reporting

Which I think, according to what you wrote, is still the case. The application isn't sending inaccurate reports, as you stated before: 

> I have had notifications turned off while trying to get everything working. I did turn on for a short time and got some notifications for "disconnected" - these were for two cell phones and two Google nest speakers. 

Let me know if I can help clarify things further,
thanks,
j

**Comment by adm2k** [comment] 2024-05-19 10:44
Here is an a screenshot from a few minutes ago. There are not in actuality 29 down. There are none down. That would be almost all y devices.
![image](https://github.com/jokob-sk/NetAlertX/assets/120423301/89d4bdd9-91a6-4dc8-9365-158b0ef24ecc)

Attached is the log file for when the above is showing.
[log.txt](https://github.com/jokob-sk/NetAlertX/files/15369003/log.txt)

Notifications are I think resolved.

As far as the Homepage Widget, here is the screenshot. As you can see it reports 1 down where NetAlertx is showing 29
![image](https://github.com/jokob-sk/NetAlertX/assets/120423301/97d5adf5-dd46-4a90-b240-da07c40aeaae)

The folks at Homepage says this:
Homepage quite literally makes no modifications whatsoever to the API output.

[homepage/src/widgets/netalertx/component.jsx](https://github.com/gethomepage/homepage/blob/97d7ae21e483c13c71c3a61ff5f18ac0b119d3f8/src/widgets/netalertx/component.jsx#L31-L34)

Lines 31 to 34 in [97d7ae2](https://github.com/gethomepage/homepage/commit/97d7ae21e483c13c71c3a61ff5f18ac0b119d3f8)

 <Block label="netalertx.total" value={t("common.number", { value: parseInt(netalertxData[0], 10) })} /> 
 <Block label="netalertx.connected" value={t("common.number", { value: parseInt(netalertxData[1], 10) })} /> 
 <Block label="netalertx.new_devices" value={t("common.number", { value: parseInt(netalertxData[3], 10) })} /> 
 <Block label="netalertx.down_alerts" value={t("common.number", { value: parseInt(netalertxData[4], 10) })} />

I am at a loss. I was hoping I could count on this great tool you have developed but telling me devices are down when they are not is a problem.

Thanks for your patience and I hope we can resolve.

**Comment by jokob-sk** [comment] 2024-05-25 00:11
I updated the titles to exclude offline devices to prevent misunderstandings: 
![image](https://github.com/jokob-sk/NetAlertX/assets/96159884/d360ec7e-fe7e-4426-ba88-0005164eb26c)

**Comment by meeowgler** [comment] 2024-05-28 17:58
How is the "Offline" device status determined during an Arp-Scan? Does it attempt to ping the device IP? Is there a way to make the timeout value configurable?

Thanks!

**Comment by jokob-sk** [comment] 2024-05-28 22:44
Hi @meeowgler ,

If you have a lot of offline devices, which should be online, look into using or substituing ARP scan with other scans, such as `NMAPDEV`. The [ARP scan protocol uses](https://networkencyclopedia.com/arp-command/) a cache so results may not be 100% reliable. You can find all available network scanning options (marked as `🔍 dev scanner`) in the [Plugins overview](https://github.com/jokob-sk/NetAlertX/blob/main/front/plugins/README.md) readme.

**Comment by jokob-sk** [comment] 2024-06-08 14:06
closing -> releasing in ~10min

**Closed by jokob-sk** 2024-06-08 14:06 UTC
Labels: next release/in dev image🚀, Setup 📥
