### ISSUE TITLE
Un-Discoverable plugin issue

### ISSUE THREAD

**Issue by systemik** [jokob-sk/NetAlertX#807] opened 2024-09-25 13:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

It seems that devices created by Un-Discoverable plugin are set with a MAC with the same name as the device. 

When we then try to assign a device to such dummy device, it fails and the error message states :

[25-Sep-2024 15:15:15 Europe/Berlin] PHP Fatal error:  Uncaught Exception: Invalid mac address in /app/front/php/server/devices.php:841

If we manually set a dummy mac address for the dummy device then we can properly assign devices to it.

### Expected Behavior

This may be fixed by either creating a dummy mac for the dummy device or by changing the assign code to avoid checking for properly formatted MAC addresses when the device is dummy.

### Steps To Reproduce

Create dummy device and try to assign a device to it in the network page.

### What branch are you running?

Production

### app.log

PHP Fatal error:  Uncaught Exception: Invalid mac address in /app/front/php/server/devices.php:841
Stack trace:
#0 /app/front/php/server/devices.php(46): updateNetworkLeaf()
#1 {main}
  thrown in /app/front/php/server/devices.php on line 841

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by systemik** [comment] 2024-09-25 13:41
When looking at the code, it seems that a random mac should have been generated with the function "string_to_mac_hash" in the undiscoverable device plugin but it does not work as expected it seems.


<img width="599" alt="image" src="https://github.com/user-attachments/assets/d7f1f22a-a053-47e7-adca-796856d60d4d">

Second issue when there is an invalid mac in the list : most devices are reported offline ...

<img width="230" alt="image" src="https://github.com/user-attachments/assets/24600455-ea65-425e-8faa-303d1278c54c">

**Comment by FlyingToto** [comment] 2024-09-25 21:22
addeddum

Expected Behavior
This may be fixed by preferably by allowing linkage to the device pseudo-MAC similar to way NaX allow to link the root firewall to the internet ISP Gateway under MAC=internet. 
or  either by creating a dummy/or updatable  mac for the dummy device or by changing the assign code to avoid checking for properly formatted MAC addresses when the device is dummy.

**Comment by jokob-sk** [comment] 2024-09-25 22:53
Thanks for the report and help @systemik , @FlyingToto - this should be fixed in the latest release in ~15 min from now -> Closing

**Closed by jokob-sk** 2024-09-25 22:53 UTC
Labels: bug 🐛, next release/in dev image🚀

**Comment by jokob-sk** [comment] 2024-09-25 23:04
@FlyingToto I was thinking of making the mac editable, but I don't yet have UI support for it - so maybe in the future

**Comment by FlyingToto** [comment] 2024-09-26 12:31
since they are static, I don't think they would need to be editable in gui per say if in the plugin config page we could load them in one shot.... something like: 
from: 
mydummydevice 
to
mydummydevice, 192.168.12.1, AA:BB:CC:DD:EE:FF, Gateway, ...
