### ISSUE TITLE
Link in HTML Email Template is wrong

### ISSUE THREAD

**Issue by ace16vitamine** [jokob-sk/NetAlertX#432] opened 2023-09-11 15:11 UTC
## Describe the issue
Link in HTML Email Template is wrong:
http://192.168.1.20:20211/deviceDetails.php?mac=78:d2:94:9f:b4:c%200

Original Link from WebUI for the same Device:
http://192.168.1.20:20211/deviceDetails.php?mac=78%3Ad2%3A94%3A9f%3Ab4%3Ac0

Seems that in the E-Mail URL is a Space in the Mac: 78:d2:94:9f:b4:c 0
![Bildschirmfoto 2023-09-11 um 17 09 04](https://github.com/jokob-sk/Pi.Alert/assets/22064392/25852016-197a-4fb9-9c40-bdfc55bf7d0b)

**Comment by jokob-sk** [comment] 2023-09-12 10:14
Regrettably, I can't seem to reproduce the error. Can you provide me with more details?

**Comment by ace16vitamine** [comment] 2023-09-12 11:29
done by mail (forward the complete email with the broken link)

**Comment by jokob-sk** [comment] 2023-09-13 21:20
Hi there!

Thanks for the details. Regrettably, I wasn't able to determine the issue and I'm not able to reproduce the error. 

The code responsible for generating the MAC links is (important: notice the use of the `mac` variable):

```python
def generate_mac_links (html, deviceUrl):

    p = re.compile(r'(?:[0-9a-fA-F]:?){12}')

    MACs = re.findall(p, html)

    for mac in MACs:
        html = html.replace('<td>' + mac + '</td>','<td><a href="' + deviceUrl + mac + '">' + mac + '</a></td>')

    return html
```

after that, the email is logged nad then sent out:

```python
    # Create clickable MAC links
    mail_html = generate_mac_links (mail_html, deviceUrl)

    #  Write output emails for debug
    write_file (logPath + '/report_output.json', json.dumps(json_final))
    write_file (logPath + '/report_output.txt', mail_text)
    write_file (logPath + '/report_output.html', mail_html)
```

If the code would be causing the issue, then we would see a space in the mac address as well as in the query string of the link, because the same variable is used. That means a space would be present at 1,2 and 3 in this screencap. 

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/5ffeaa83-67b1-4e91-b47d-407e135b6f13)

However the space is only present in the link (3).

It could be that the email service itself is causing the issue. You seem to be using a less-know email service (compared to e.g. gmail or outlook). Would it be possible to switch to one of those for testing and see if the issue re-occurs?

**Comment by ace16vitamine** [comment] 2023-09-13 22:01
Hi,

thank you for your great support (and for your Time...).

We are using our own infrastructure, but I can switch to gmail for example for testing. This issue seems only for the reported MAC, I mean it is no drama.

GMX is not possible. I found some days ago another issue (#285) what I can confirm, tested with the dev version. I remember  this issue was present in a fork, but I can't remember exactly which and I do not now if there was an issue opened.

I can test it tomorrow Jokob

Have an nice evening
Stefan

**Comment by jokob-sk** [comment] 2023-09-14 12:25
Hey there,

just noticed the same "space issue" in a different screenshot you provided. I think this again points to an issue with the email service, not PiAlert:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/f1bf2120-f039-4dd9-b197-8c1909e135b0)

You can configure GMX as per this guide: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/SMTP.md

**Comment by jokob-sk** [comment] 2023-09-20 10:04
closing due to no activity, will reopen if needed

**Comment by LaurentAtJoes** [comment] 2024-10-26 21:42
Hi there,

I'm also experiencing the extra space in the mac string used in href=
I'm using an email service from a "big" french hosting services provider (OVH).

One thing I noticed by looking at the email source in a text editor :
it's actually a new line (CR+LF here), and the position of last character (in my case, the colon) of the previous line (in my case, the colon) is 999

It might be a long shot here, but could it be that some email servers have a line length limit <1000 and then force-split them ?

![image](https://github.com/user-attachments/assets/bb30f6e0-fcad-4d50-b0b9-fa5c430442cd)

**Comment by jokob-sk** [comment] 2024-10-27 00:12
It's possible. A lot of people are using Gmail an smtp server. If that works then the issue is on the SMTP server side. https://github.com/jokob-sk/NetAlertX/blob/main/docs/SMTP.md

**Comment by LaurentAtJoes** [comment] 2024-10-27 22:52
Yeah, the only thing that would come to mind, is to force a line break somewhere "safe" on your side (if that's even possible).
like format the table block so it isn't sent as a single line
`<table...
    <th...
    <tr...
        <td></td>
    </tr>
</table>`

otherwise, that's not a huge issue, although the link to the device in the alert email does come in handy.

**Comment by jokob-sk** [comment] 2024-10-28 00:51
Hummm, not sure how to do it on the application side though. It's possible that the email server itself is concatenating every X characters with a line break? not sure... I am all ears if you have ideas how to prevent it from my side.

**Comment by jokob-sk** [comment] 2024-11-05 21:21
No reply for a week -> closing

**Closed by jokob-sk** 2024-11-05 21:21 UTC
Labels: Waiting for reply⏳

**Comment by jokob-sk** [comment] 2024-11-09 20:05
This has been confirmed being caused by a 3rd party application, in the case of #879 it was caused by the ScrolloutF1 app.
