### ISSUE TITLE
Pi.Alert to Net Alert doesn't migrate database and devices

### ISSUE THREAD

**Issue by catalans1980** [jokob-sk/NetAlertX#633] opened 2024-04-17 13:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

I have updated my Pi.Alert to Net Alert on my nas by updating the stack on portainer changing the image and the folders as asked. In the migration manual was written that "The application will auto-migrate the database, config, and all device information" but i don't have neither the devices or any data.

### Expected Behavior

The application will auto-migrate the database, config, and all device information

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by catalans1980** [comment] 2024-04-17 14:50
Ended up having to manually upload the pialert.conf and pialert.db with the name changed to app.conf and app.db to the folder when the app was starting. If i added it with the docker on exited/paused, it auto-reseted on the previous app.db. Well, i think it's all right now, but it shouldn't be like this, feels dirty

**Comment by edd080** [comment] 2024-04-17 16:11
I am getting the same exact issue after  changing the folders as described and launching netalert i noticed that I had no devices listed and all the settings disappeared, @catalans1980  would it be possible to let me know how you managed to get it to work exactly? I am abit new to this so I appreciate your patience 😁, thanks.

**Comment by chilicheech** [comment] 2024-04-17 17:48
I'm seeing the same issue and would appreciate instructions on how to fix it.

**Comment by chilicheech** [comment] 2024-04-17 18:18
ok, so what i did was i renamed all pialert files in config and db to app and that worked.

**Comment by jokob-sk** [comment] 2024-04-17 21:28
The mount points should be renamed/moved only after the new image is launched. What happens is:

1. The app starts
2. Check if there is a /home/pi/ folder with old files
3. If yes, moves them in the new location + renames the files

If you change the mount points beforehand the app can't find your old files. That's what I assume is happening. I will explicitly say inteh migration guide to only do that after the app was first launched. Hope this will prevent these issues.

**Comment by necromancyr** [comment] 2024-04-17 21:56
The migration guide isn't clear, and what you described above isn't actually happening (at least not w/the Unraid container).    The files aren't copied, but you do get a message saying "old install detected, follow guide" which...I guess says to change the container locations?  

It's really not clear if you should run NetAlertX once with the new folder mapping or the old folder mapping, when you should change the mapping (after running once?)

The Unraid container for NetAlertX, for example, has the container paths set to the old PiAlert paths.  I figured that was intended, ran it, got the "see this to migrate" message, changed the container paths (not touching the host paths/mapping), and then restarted and a clean/new setup vs. migration happened.

**Comment by necromancyr** [comment] 2024-04-17 22:01
The Unraid container seems to have things mapped to the old locations and doesn't seem to copy anything to new file names/locations/etc.  What's the intent for migrating there (and getting the message at the top saying "Follow these directions to migrate", which suggest changing the container paths in the config but doing that just gets you a clean/wiped setup.

**Comment by jokob-sk** [comment] 2024-04-17 22:12
I made the above guide even more explicit, please let me know how to adjust the guide further to clarify any misunderstandings:

https://github.com/jokob-sk/NetAlertX/blob/main/docs/MIGRATION.md

**Comment by necromancyr** [comment] 2024-04-17 22:22
What you added seems to conflict with this:
_In short: The application will auto-migrate the database, config, and all device information. A ticker message on top will be displayed until you update your docker mount points. Even so, it's always good to have a [backup strategy](https://github.com/jokob-sk/NetAlertX/blob/main/docs/BACKUPS.md) in place._

That says it will rename the files automatically, but the new instructions say to do it manually. Either way is fine, just make it explicit that you have to do XYZ or people will get confused.

Also, is there any reason not to just rename the files and use the new docker/paths?  Is something getting changed in the files themselves (paths in the DB or something) or is it just naming/location that changed?  Basically, it's not clear why you need to run the docker once before migrating. 

Also, ONLY the pialert.db and pi-alert.conf need to be renamed, right?  There are other files in the directories (device lists in csv and backups, etc.) - nothing critical there?

**Comment by necromancyr** [comment] 2024-04-17 22:29
Ok.  That worked - manually renaming the two files and changing the mapped folders.  

Not sure if something needs it to be run using the old mapping first, but it definitely makes it more confusing (on Unraid at least).

**Comment by jokob-sk** [comment] 2024-04-17 22:34
Glad to hear that the updated guide makes things clearer. And yes, the db and config are the only files that are needed to bring everything over.

Unfortunately I don't run unraid and I will always have to rely on the community to provide feedback for their specific setups. So this feedback is really great to improve things for everyone.

Thanks for the patience and help,
J

**Comment by edd080** [comment] 2024-04-18 08:20
I copied the app.conf and app.db files once again and put the image down and up again using docker compose. I dont know if it was the copy and paste or putting the site down and up again, but this seemed to solve my issue. Site is back up and running using the new paths.
It certainly was not straightforward for me but at least I did not lose my devices and settings.
Thanks.

**Comment by jokob-sk** [comment] 2024-04-18 08:52
Thanks for all the input.

> 1.     The app starts
> 2.     Check if there is a /home/pi/ folder with old files
> 3.     If yes, moves them in the new location + renames the files


The code responsible for creating symlinks is the one below:

```bash
# 🔻 FOR BACKWARD COMPATIBILITY - REMOVE AFTER 12/12/2024

# Check if pialert.db exists, then create a symbolic link to app.db
if [ -f "${INSTALL_DIR_OLD}/db/${OLD_APP_NAME}.db" ]; then
    ln -s "${INSTALL_DIR_OLD}/db/${OLD_APP_NAME}.db" "${FULL_FILEDB_PATH}"
fi

# Check if ${OLD_APP_NAME}.conf exists, then create a symbolic link to app.conf
if [ -f "${INSTALL_DIR_OLD}/config/${OLD_APP_NAME}.conf" ]; then
    ln -s "${INSTALL_DIR_OLD}/config/${OLD_APP_NAME}.conf" "${INSTALL_DIR}/config/${CONF_FILE}"
fi
# 🔺 FOR BACKWARD COMPATIBILITY - REMOVE AFTER 12/12/2024

```

so yes, the last point is not correct:


 > If yes, moves them in the new location + renames the files


it should say:

>3. If yes, creates the symlinks to files the new /app/ folders

**Comment by necromancyr** [comment] 2024-04-18 13:47
So...given it's a container...why does it matter where on host it's linked?  

Theoretically, if the person maps in their pialert directories, NetAlertX should just detect the files are there (and named pialert.conf vs. app.conf, etc.), rename/convert them, and done.  No need for further modification.  

Again, I may be missing something though.  

(And appreciate you're openness to feedback - realize tone/intent is sometimes lost in text back and forth, all is coming from a desire to help! :))

**Comment by necromancyr** [comment] 2024-04-22 18:41
I think the migration process makes sense - just wasn't sure about what was intended to happen automatically vs. manual so that's the key difference.  And good point re: the mapping files directly - that itself seems like a bad idea (as you note) but...guess some people would still do it!  

And it's always good to assume the best - least, I try to.  (And I think one of the unedited deleted was prob. one of mine - re-read it after submitting and realized "Huh, this doesn't read the way I want to to and I sound like a jerk.").

**Comment by jokob-sk** [comment] 2024-04-22 21:07
Thank you for the feedback @necromancyr - glad it makes sense now.

Appreciate the honesty and message. Looking forward to collaboration on this project if you decide to feedback or even help out 😉

**Comment by Heronimos** [comment] 2024-04-26 13:15
I tried a lot of different way.  But I can't get a migration.  
Even a clean container where I only copy the app.conf and app.db  (the renamed files) don't work. 

A inplace upgrade (only change in pulled imange) will not work.  Then I only get a loadingscreen, but no devices.

**Comment by jokob-sk** [comment] 2024-05-09 04:04
released/workaround provided -> closing for now

**Closed by jokob-sk** 2024-05-09 04:04 UTC
Labels: bug 🐛, Workaround provided ⚒️

**Comment by Compizfox** [comment] 2024-10-31 15:05
Just tried the migration but have the same issue as @edd080. After changing the mounts and deploying the container, all my devices were gone. So I stopped the container and moved `pialert.db` to `app.db` and `pialert.conf` to `app.conf`. However, now I get this error:

> Open DB Error: database disk image is malformed

**Comment by jokob-sk** [comment] 2024-10-31 20:12
Regrettably I can't help with a corrupted DB. You can try restoring it from a backup, if you have one, or using the devices.csv file to restore most of the setup. See this for more details:

https://github.com/jokob-sk/NetAlertX/blob/main/docs/BACKUPS.md
https://github.com/jokob-sk/NetAlertX/blob/main/docs/MIGRATION.md

You can try to move the DB back and see if runs and try again. Sometimes there might be additional wal files that were left behind which could cause the issue. Make sure you move everything from those folders
