### ISSUE TITLE
INTRSPD - Internet Speedtest Plugin not showing the Download Speed under "Plugin Objects

### ISSUE THREAD

**Issue by Stationary-1** [jokob-sk/NetAlertX#854] opened 2024-10-19 14:21 UTC
### Is there an existing issue for this?

- [x] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

Under Integrations > Plugins > Internet speedtest on the tab "Plugin Objects" only the "Upload Speed" shows up, but not the "Download Speed". This was tried and confirmed on various devices: iPad with Safari, MacBook with Safari or Firefox, Raspberry Pi5 with Chromium or Firefox.

### Expected Behavior

Left to the green bar with the upload speed, a green bar with the download speed is expected. 

### Steps To Reproduce

1) Settings for Internet Speedtest: "schedule" "0 */6 * * *", Run timeout 300, Watched 0 items, Report on 0 items
2) once speedtests have run, go to Integration > Plugins > Internet speedtest, check on the tab "Plugin Objects"

This happens on both the production branch and the dev branch (I am currently using the latter built on 2024-10-19 for your recommendation given in another forum, thanks again for that!!).

From currently used DEV branch:
![netalertx](https://github.com/user-attachments/assets/3919f340-b4e7-470e-9777-65b8614a6771)
![IMG_1954](https://github.com/user-attachments/assets/f5621ab0-9469-4e74-b730-860f2221e335)

From previously used PRODUCTION branch:
![IMG_1951](https://github.com/user-attachments/assets/9caee0d7-77d6-46d7-a82f-b32c3cf5a0dd)

I have seen the image you have shown me on another forum, where the green bar(s) under Download were present, but I have not been able to reproduce that, neither with cleared browser caches, reloaded pages or a freshly installed container.

### app.conf

```python
#-----------------AUTOGENERATED FILE-----------------#
#                                                    #
#         Generated:  2024-10-19_11-31-51            #
#                                                    #
#   Config file for the LAN intruder detection app:  #
#      https://github.com/jokob-sk/NetAlertX         #
#                                                    #
#-----------------AUTOGENERATED FILE-----------------#


# General
#---------------------------
LOADED_PLUGINS=['ARPSCAN','CSVBCKP','DBCLNP','INTRNT','MAINT','NEWDEV','NSLOOKUP','NTFPRCS','AVAHISCAN','SETPWD','SMTP','SYNC','VNDRPDT','WORKFLOWS','INTRSPD']
LOADED_PLUGINS__metadata="                      {}\n                    "
SCAN_SUBNETS=['xxx.xxx.xxx.0/24 --interface=eth0']
SCAN_SUBNETS__metadata="                      {}\n                    "
LOG_LEVEL='verbose'
LOG_LEVEL__metadata="                      {}\n                    "
TIMEZONE='xxx/xxx'
TIMEZONE__metadata="                      {}\n                    "
PLUGINS_KEEP_HIST=250
PLUGINS_KEEP_HIST__metadata="                      {}\n                    "
REPORT_DASHBOARD_URL='http://netalertx'
REPORT_DASHBOARD_URL__metadata="                      {}\n                    "
DAYS_TO_KEEP_EVENTS=90
DAYS_TO_KEEP_EVENTS__metadata="                      {}\n                    "
HRS_TO_KEEP_NEWDEV=0
HRS_TO_KEEP_NEWDEV__metadata="                      {}\n                    "
CLEAR_NEW_FLAG=0
CLEAR_NEW_FLAG__metadata="                      {}\n                    "
API_CUSTOM_SQL='SELECT * FROM Devices WHERE dev_PresentLastScan = 0'
API_CUSTOM_SQL__metadata="                      {}\n                    "
VERSION='1729324699'
VERSION__metadata="                      {}\n                    "
NETWORK_DEVICE_TYPES=['AP','Gateway','Firewall','Hypervisor','Powerline','Switch','WLAN','PLC','Router','USB LAN Adapter','USB WIFI Adapter','Internet']
NETWORK_DEVICE_TYPES__metadata="                      {}\n                    "


# INTRSPD
#---------------------------
INTRSPD_RUN='schedule'
INTRSPD_RUN__metadata="                      {\"function\": \"RUN\", \"events\": [\"run\"], \"type\": {\"dataType\": \"string\", \"elements\": [{\"elementType\": \"select\", \"elementOptions\": [], \"transformers\": []}]}, \"default_value\": \"disabled\", \"options\": [\"disabled\", \"once\", \"schedule\", \"always_after_scan\"], \"localized\": [\"name\", \"description\"], \"name\": [{\"language_code\": \"en_us\", \"string\": \"When to run\"}, {\"language_code\": \"es_es\", \"string\": \"Cuando ejecuta\"}, {\"language_code\": \"de_de\", \"string\": \"Wann ausf\\u00fchren\"}], \"description\": [{\"language_code\": \"en_us\", \"string\": \"Enable a regular internet speedtest. If you select <code>schedule</code> the scheduling settings from below are applied. If you select <code>once</code> the scan is run only once on start of the application (container) for the time specified in <a href=\\\"#INTRSPD_RUN_TIMEOUT\\\"><code>INTRSPD_RUN_TIMEOUT</code> setting</a>.\"}, {\"language_code\": \"de_de\", \"string\": \"Aktiviere periodische Internetgeschwindigkeitstests. Wenn <code>schedule</code> ausgew\\u00e4hlt ist, werden die Einstellungen von unten genutzt. Bei <code>once</code> wird der Test nur einmal beim Start der Applikation (Container) f\\u00fcr die unten in der <a href=\\\"#INTRSPD_RUN_TIMEOUT\\\"><code>INTRSPD_RUN_TIMEOUT</code> Einstellung</a> gesetzten Zeit durchgef\\u00fchrt.\"}]}\n                    "
INTRSPD_CMD='python3 /app/front/plugins/internet_speedtest/script.py'
INTRSPD_CMD__metadata="                      {\"function\": \"CMD\", \"type\": {\"dataType\": \"string\", \"elements\": [{\"elementType\": \"input\", \"elementOptions\": [{\"readonly\": \"true\"}], \"transformers\": []}]}, \"default_value\": \"python3 /app/front/plugins/internet_speedtest/script.py\", \"options\": [], \"localized\": [\"name\", \"description\"], \"name\": [{\"language_code\": \"en_us\", \"string\": \"Command\"}, {\"language_code\": \"es_es\", \"string\": \"Comando\"}, {\"language_code\": \"de_de\", \"string\": \"Befehl\"}], \"description\": [{\"language_code\": \"en_us\", \"string\": \"Command to run\"}, {\"language_code\": \"es_es\", \"string\": \"Comando a ejecutar\"}, {\"language_code\": \"de_de\", \"string\": \"Auszuf\\u00fchrender Befehl\"}]}\n                    "
INTRSPD_RUN_SCHD='0 */6 * * *'
INTRSPD_RUN_SCHD__metadata="                      {\"function\": \"RUN_SCHD\", \"type\": {\"dataType\": \"string\", \"elements\": [{\"elementType\": \"input\", \"elementOptions\": [], \"transformers\": []}]}, \"default_value\": \"*/30 * * * *\", \"options\": [], \"localized\": [\"name\", \"description\"], \"name\": [{\"language_code\": \"en_us\", \"string\": \"Schedule\"}, {\"language_code\": \"es_es\", \"string\": \"Schedule\"}, {\"language_code\": \"de_de\", \"string\": \"Zeitplan\"}], \"description\": [{\"language_code\": \"en_us\", \"string\": \"Only enabled if you select <code>schedule</code> in the <a href=\\\"#INTRSPD_RUN\\\"><code>INTRSPD_RUN</code> setting</a>. Make sure you enter the schedule in the correct cron-like format (e.g. validate at <a href=\\\"https://crontab.guru/\\\" target=\\\"_blank\\\">crontab.guru</a>). For example entering <code>0 4 * * *</code> will run the scan after 4 am in the <a onclick=\\\"toggleAllSettings()\\\" href=\\\"#TIMEZONE\\\"><code>TIMEZONE</code> you set above</a>. Will be run NEXT time the time passes.\"}, {\"language_code\": \"es_es\", \"string\": \"Solo habilitado si selecciona <code>schedule</code> en la configuraci\\u00f3n <a href=\\\"#INTRSPD_RUN\\\"><code>INTRSPD_RUN</code></a>. Aseg\\u00farese de ingresar el schedule en el formato similar a cron correcto (por ejemplo, valide en <a href=\\\"https://crontab.guru/\\\" target=\\\"_blank\\\">crontab.guru</a>). Por ejemplo, ingrese <code >0 4 * * *</code> ejecutar\\u00e1 el escaneo despu\\u00e9s de las 4 am en el <a onclick=\\\"toggleAllSettings()\\\" href=\\\"#TIMEZONE\\\"><code>TIMEZONE</code> que configur\\u00f3 arriba </a>. Se ejecutar\\u00e1 la PR\\u00d3XIMA vez que pase el tiempo.\"}, {\"language_code\": \"de_de\", \"string\": \"Nur aktiv, wenn <code>schedule</code> in der <a href=\\\"#INTRSPD_RUN\\\"><code>INTRSPD_RUN</code> Einstellung</a> ausgew\\u00e4hlt wurde. Sichergehen, dass das Intervall in einem korrekten cron-\\u00e4hnlichen Format angegeben wurde (z.B. auf <a href=\\\"https://crontab.guru/\\\" target=\\\"_blank\\\">crontab.guru</a> testen). <code>0 4 * * *</code> w\\u00fcrde den Scan t\\u00e4glich um 4 Uhr in der <a onclick=\\\"toggleAllSettings()\\\" href=\\\"#TIMEZONE\\\">oben ausgew\\u00e4hlten <code>TIMEZONE</code></a> starten. Wird erst beim N\\u00c4CHSTEN Intervall ausgef\\u00fchrt. <br/>Es wird empfohlen, das Intervall aller Plugins, welche nach neuen Ger\\u00e4ten suchen, auf den gleichen Wert zu setzen.\"}]}\n                    "
INTRSPD_RUN_TIMEOUT=300
INTRSPD_RUN_TIMEOUT__metadata="                      {\"function\": \"RUN_TIMEOUT\", \"type\": {\"dataType\": \"integer\", \"elements\": [{\"elementType\": \"input\", \"elementOptions\": [{\"type\": \"number\"}], \"transformers\": []}]}, \"default_value\": 60, \"options\": [], \"localized\": [\"name\", \"description\"], \"name\": [{\"language_code\": \"en_us\", \"string\": \"Run timeout\"}, {\"language_code\": \"es_es\", \"string\": \"Tiempo de espera de ejecuci\\u00f3n\"}, {\"language_code\": \"de_de\", \"string\": \"Zeitlimit\"}], \"description\": [{\"language_code\": \"en_us\", \"string\": \"Maximum time in seconds to wait for the script to finish. If this time is exceeded the script is aborted.\"}, {\"language_code\": \"es_es\", \"string\": \"Tiempo m\\u00e1ximo en segundos para esperar a que finalice el script. Si se supera este tiempo, el script se cancela.\"}, {\"language_code\": \"de_de\", \"string\": \"Maximale Zeit in Sekunden, die auf den Abschluss des Skripts gewartet werden soll. Bei \\u00dcberschreitung dieser Zeit wird das Skript abgebrochen.\"}]}\n                    "
INTRSPD_WATCH=[]
INTRSPD_WATCH__metadata="                      {\"function\": \"WATCH\", \"type\": {\"dataType\": \"array\", \"elements\": [{\"elementType\": \"select\", \"elementOptions\": [{\"multiple\": \"true\"}], \"transformers\": []}]}, \"default_value\": [], \"options\": [\"Watched_Value1\", \"Watched_Value2\", \"Watched_Value3\", \"Watched_Value4\"], \"localized\": [\"name\", \"description\"], \"name\": [{\"language_code\": \"en_us\", \"string\": \"Watched\"}, {\"language_code\": \"es_es\", \"string\": \"Visto\"}, {\"language_code\": \"de_de\", \"string\": \"\\u00dcberwacht\"}], \"description\": [{\"language_code\": \"en_us\", \"string\": \"Send a notification if selected values change. Use <code>CTRL + Click</code> to select/deselect. <ul> <li><code>Watched_Value1</code> is Download speed (not recommended)</li><li><code>Watched_Value2</code> is Upload speed (not recommended)</li><li><code>Watched_Value3</code> unused </li><li><code>Watched_Value4</code> unused </li></ul>\"}, {\"language_code\": \"de_de\", \"string\": \"Sende eine Benachrichtigung, wenn ein ausgw\\u00e4hlter Wert sich \\u00e4ndert. <code>STRG + klicken</code> zum aus-/abw\\u00e4hlen. <ul> <li><code>Watched_Value1</code> ist die Download-Geschwindigkeit (nicht empfohlen)</li><li><code>Watched_Value2</code> ist die Upload-Geschwindigkeit (nicht empfohlen)</li><li><code>Watched_Value3</code> ist nicht in Verwendung </li><li><code>Watched_Value4</code> ist nicht in Verwendung </li></ul>\"}]}\n                    "
INTRSPD_REPORT_ON=[]
INTRSPD_REPORT_ON__metadata="                      {\"function\": \"REPORT_ON\", \"type\": {\"dataType\": \"array\", \"elements\": [{\"elementType\": \"select\", \"elementOptions\": [{\"multiple\": \"true\"}], \"transformers\": []}]}, \"default_value\": [], \"options\": [\"new\", \"watched-changed\", \"watched-not-changed\", \"missing-in-last-scan\"], \"localized\": [\"name\", \"description\"], \"name\": [{\"language_code\": \"en_us\", \"string\": \"Report on\"}, {\"language_code\": \"es_es\", \"string\": \"Informar sobre\"}, {\"language_code\": \"de_de\", \"string\": \"Benachrichtige wenn\"}], \"description\": [{\"language_code\": \"en_us\", \"string\": \"Send a notification only on these statuses. <code>new</code> means a new unique (unique combination of PrimaryId and SecondaryId) object was discovered. <code>watched-changed</code> means that selected <code>Watched_ValueN</code> columns changed.\"}, {\"language_code\": \"es_es\", \"string\": \"Env\\u00ede una notificaci\\u00f3n solo en estos estados. <code>new</code> significa que se descubri\\u00f3 un nuevo objeto \\u00fanico (combinaci\\u00f3n \\u00fanica de PrimaryId y SecondaryId). <code>watched-changed</code> significa que seleccion\\u00f3 <code>Watched_ValueN Las columnas </code> cambiaron.\"}, {\"language_code\": \"de_de\", \"string\": \"Benachrichtige nur bei diesen Status. <code>new</code> bedeutet ein neues eindeutiges (einzigartige Kombination aus PrimaryId und SecondaryId) Objekt wurde erkennt. <code>watched-changed</code> bedeutet eine ausgew\\u00e4hlte <code>Watched_ValueN</code>-Spalte hat sich ge\\u00e4ndert.\"}]}\n                    "
```

### docker-compose.yml

```python
version: "3.01"
services:
  netalertx:
    container_name: netalertx-dev
    # use the below line if you want to test the latest dev image
    # image: "jokobsk/netalertx-dev:latest" 
    image: "jokobsk/netalertx-dev:latest"      
    network_mode: "host"        
    restart: unless-stopped
    volumes:
      - /opt/netalertx-dev/config:/app/config
      - /opt/netalertx-dev/db/:/app/db/      
      # (optional) useful for debugging if you have issues setting up the container
      # - /opt/netalertx/log:/app/front/log
      - /opt/netalertx-dev/log:/app/front/log
    environment:
      - TZ=Europe/Berlin      
      - PORT=20211
```

### What branch are you running?

Dev

### app.log

it occurs always for me. I had to shorten the app.conf when submitting it said: maximum 65536 characters

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment] 2024-10-19 21:34
Hi @Stationary-1 ,

Thanks a lot for the detailed description. This helps a lot when debugging things and reducing back and forth questions 👍

It's weird that for me the download speed shows up. Can you try one of the following?

1. You can send the app.log to my email netalertx@gmail.com or jokob.sk@gmail.com (let me know once you do - sometimes I miss it because it lands in SPAM).
2. Can you post the part of the log where the SPDTEST plugin is executed? 


You can run the plugin manually if you are not sure that the app.log contains the relevant section.  SSH into the container and run `python3 /app/front/plugins/internet_speedtest/script.py` if needed.

I'm looking for the log entry (you can search your existing log if you can find it - this is only available in the netalertx-dev branch for now - which I think you are running):

`[INTRSPD] Result (down|up)`

The whole log entry should look something like:

```
03:31:32 [INTRSPD] Result (down|up): 32.79 Mbps|19.18 Mbps
03:31:32 [Plugins] Processing file "/app/front/plugins/internet_speedtest/last_result.log"
03:31:32 [Plugins] SUCCESS, received 1 entries
03:31:32 [Plugins] sqlParam entries: [(0, 'INTRSPD', 'Speedtest', '2024-10-20 03:31:32+11:00', 'null', '2024-10-20 03:31:32', '32.79', '19.18', 'null', 'null', 'not-processed', 'null', 'null', 'null', '', '', '', '', '')]
03:31:32 [Plugins] Processing        : INTRSPD
03:31:32 [Plugins] Existing objects from Plugins_Objects: 2568
03:31:32 [Plugins] Logged events from the plugin run    : 1
03:31:32 [Plugins] pluginEvents      count: 1
03:31:32 [Plugins] pluginObjects     count: 2569
03:31:32 [Plugins] events_to_insert  count: 0
03:31:32 [Plugins] history_to_insert count: 2569
03:31:32 [Plugins] objects_to_insert count: 1
03:31:32 [Plugins] objects_to_update count: 2568
```
I also noticed some console errors in your screenshot, can you switch to the browser console and share those? 

![image](https://github.com/user-attachments/assets/790dc9e0-38ef-4bf9-a4d4-97f4c5816107)

Hope the above will give me hints what to fix. 

Thanks in advance,
j

**Comment by Stationary-1** [comment] 2024-10-20 09:14
Let me start with the errors shown in the console:
![err1](https://github.com/user-attachments/assets/dde19c2c-696f-4102-b7b4-33a24f373b1b)
![err2](https://github.com/user-attachments/assets/b57eb2eb-356c-4af9-8904-e61b5b4ec228)
![err3](https://github.com/user-attachments/assets/ace25426-0f41-4b16-b61f-08834d45d13a)
![err4](https://github.com/user-attachments/assets/b923b546-8b69-4a29-9ad7-d82757ba4ceb)
![err5](https://github.com/user-attachments/assets/f03fb063-5839-4ed1-bdf5-159bfabffb0c)
![err6](https://github.com/user-attachments/assets/97d5ecd5-6651-4961-9f58-8006d05e6683)
![err7](https://github.com/user-attachments/assets/f9634802-b34d-4e16-8e2f-19aa27e140ea)

The log will follow in the next message.

**Comment by Stationary-1** [comment] 2024-10-20 09:19
These are the message displayed in the console:

(1)
![err1](https://github.com/user-attachments/assets/044fc2b6-11a7-4fb1-b49a-da9b0251eb32)

(2)
![err2](https://github.com/user-attachments/assets/0d4a762e-4890-411a-a367-5051d7a94162)

(3)
![err3](https://github.com/user-attachments/assets/4f3ab1f8-ee2d-4aa0-8b0b-775bd3225cd0)

(4)
![err4](https://github.com/user-attachments/assets/0991a6f1-7f07-492a-8431-f2238094f73a)

(5)
![err5](https://github.com/user-attachments/assets/bee34a25-5659-4954-a1df-ca88ee8b8d16)

(6)
![err6](https://github.com/user-attachments/assets/eaa0bfca-def9-4e6a-a16e-339277238d30)

(7)
![err7](https://github.com/user-attachments/assets/14fb697a-0194-4b8f-afe8-9a554c466b5f)

The app.log data will follow in the next message.

**Comment by Stationary-1** [comment] 2024-10-20 09:30
This is the app.log entry for the INTRSPD which I have run now manually:

11:19:38 [MAIN] Process: Wait
11:20:24 [2024-10-20 11:20:24+02:00] START Run: INTRSPD
11:20:24 [Plugins] Executing: python3 /app/front/plugins/internet_speedtest/script.py
11:20:25 [INTRSPD] In script
11:20:48 [INTRSPD] Result (down|up): 78.05 Mbps|24.45 Mbps
11:20:48 [HELPER] â  ERROR not processed set_type:  {'dataType': 'string', 'elements': [{'elementType': 'input', 'elementOptions': [{'cssClasses': 'col-xs-12'}], 'transformers': []}, {'elementType': 'button', 'elementOptions': [{'getStringKey': 'Gen_Generate'}, {'customParams': 'SYNC_encryption_key'}, {'onClick': 'generateApiToken(this, 30)'}, {'cssClasses': 'col-xs-12'}], 'transformers': []}]} 
11:20:48 [HELPER] â  ERROR not processed set_value:  
11:20:48 [Plugins] SUCCESS, received 1 entries
11:20:48 [API] Updating table_appevents.json file in /front/api
11:20:48 [API] Updating table_plugins_history.json file in /front/api
11:20:48 [API] Updating table_plugins_objects.json file in /front/api
11:20:48 [2024-10-20 11:20:48+02:00] END Run: INTRSPD
11:20:53 [Plugin utils] ---------------------------------------------


The one which has run automatically this morning looks like this:

06:01:10 [Plugin utils] ---------------------------------------------
06:01:10 [Plugin utils] display_name: Internet speedtest
06:01:10 [Plugins] Executing: python3 /app/front/plugins/internet_speedtest/script.py
06:01:10 [INTRSPD] In script
06:01:31 [INTRSPD] Result (down|up): 135.74 Mbps|29.95 Mbps
06:01:32 [HELPER] â  ERROR not processed set_type:  {'dataType': 'string', 'elements': [{'elementType': 'input', 'elementOptions': [{'cssClasses': 'col-xs-12'}], 'transformers': []}, {'elementType': 'button', 'elementOptions': [{'getStringKey': 'Gen_Generate'}, {'customParams': 'SYNC_encryption_key'}, {'onClick': 'generateApiToken(this, 30)'}, {'cssClasses': 'col-xs-12'}], 'transformers': []}]} 
06:01:32 [HELPER] â  ERROR not processed set_value:  
06:01:32 [Plugins] SUCCESS, received 1 entries
06:01:32 [API] Updating table_appevents.json file in /front/api
06:01:32 [API] Updating table_plugins_history.json file in /front/api
06:01:32 [API] Updating table_plugins_objects.json file in /front/api
06:01:32 [Process Scan]  Exclude ignored devices
06:01:32 [Process Scan]  Processing scan results
06:01:32 [Process Scan] Print Stats
06:01:32 [Scan Stats] Devices Detected.......: 21
06:01:32 [Scan Stats] New Devices............: 0
06:01:32 [Scan Stats] Down Alerts............: 0
06:01:32 [Scan Stats] New Down Alerts........: 0
06:01:32 [Scan Stats] New Connections........: 10
06:01:32 [Scan Stats] Disconnections.........: 1
06:01:32 [Scan Stats] IP Changes.............: 4
06:01:32 [Scan Stats] Scan Method Statistics:
06:01:32     INTRNT: 1
06:01:32     arp-scan: 19
06:01:32     local_MAC: 1
06:01:32 [Process Scan] Stats end
06:01:32 [Process Scan] Sessions Events (connect / disconnect)
06:01:32 [Process Scan] Creating new devices
06:01:32 [Process Scan] Updating Devices Info
06:01:32 [Process Scan] Voiding false (ghost) disconnections
06:01:32 [Process Scan] Pairing session events (connection / disconnection) 
06:01:32 [Process Scan] Creating sessions snapshot
06:01:32 [Process Scan] Inserting scan results into Online_History
06:01:32 [Process Scan] Skipping repeated notifications
06:01:32 [Skip Repeated Notifications] Skip Repeated
06:01:32 [Plugin utils] ---------------------------------------------

**Comment by jokob-sk** [comment] 2024-10-20 09:56
Hi @Stationary-1 ,

Thanks a lot! I cam see that this indicates that the data is captured by the plugin:

```
06:01:31 [INTRSPD] Result (down|up): 135.74 Mbps|29.95 Mbps
```

Hummm, can you also post the app.log line where the data gets saved in the DB, something like:

```
03:31:32 [Plugins] sqlParam entries: [(0, 'INTRSPD', 'Speedtest', '2024-10-20 03:31:32+11:00', 'null', '2024-10-20 03:31:32', '32.79', '19.18', 'null', 'null', 'not-processed', 'null', 'null', 'null', '', '', '', '', '')]
```
If it's not in your log, make sure the `LOG_LEVEL` is set to `debug`. I want to make sure the data is passed to the SQL query correctly. 

Just checking, in the Integrations -> Plugins -> Internet speed -> Events History - are the data in there or are they missing too?

Thanks in advance!

**Comment by Stationary-1** [comment] 2024-10-20 10:31
> in the Integrations -> Plugins -> Internet speed -> Events History - are the data in there or are they missing too?

There the data is visible:
![speed1](https://github.com/user-attachments/assets/54478b90-bdeb-4f7b-8535-7b1d993bbce6)

I also have an interesting one for you:
Where the speedtest has been initiated manually, in one case both up and down is filled in the plugin objects (11:20) in another case (12:25) not. When it runs automatically, so far it only shows the upload:
![speed2](https://github.com/user-attachments/assets/cdebf2c4-e962-4722-9241-7388df701a9c)

I'll check the log with log_level debug and post that in the next message.

**Comment by Stationary-1** [comment] 2024-10-20 10:37
app.log with log level set to debug:
12:33:56 [2024-10-20 12:33:56+02:00] START Run: INTRSPD
12:33:56 [Plugins] Timeout: 300
12:33:56 [Plugin utils] Pre-Resolved CMD: python3/app/front/plugins/internet_speedtest/script.py
12:33:56 [Plugins] Executing: python3 /app/front/plugins/internet_speedtest/script.py
12:33:56 [Plugins] Resolved : ['python3', '/app/front/plugins/internet_speedtest/script.py']
12:33:56 [INTRSPD] In script
12:34:17 [INTRSPD] Result (down|up): 133.5 Mbps|29.69 Mbps
12:34:17 [HELPER] ⚠ ERROR not processed set_type:  {'dataType': 'string', 'elements': [{'elementType': 'input', 'elementOptions': [{'cssClasses': 'col-xs-12'}], 'transformers': []}, {'elementType': 'button', 'elementOptions': [{'getStringKey': 'Gen_Generate'}, {'customParams': 'SYNC_encryption_key'}, {'onClick': 'generateApiToken(this, 30)'}, {'cssClasses': 'col-xs-12'}], 'transformers': []}]} 
12:34:17 [HELPER] ⚠ ERROR not processed set_value:  
12:34:17 [Plugins] Processing file "/app/front/plugins/internet_speedtest/last_result.log"
12:34:17 [Plugins] SUCCESS, received 1 entries
12:34:17 [Plugins] sqlParam entries: [(0, 'INTRSPD', 'Speedtest', '2024-10-20 12:34:17+02:00', 'null', '2024-10-20 12:34:17', '133.5', '29.69', 'null', 'null', 'not-processed', 'null', 'null', 'null', '', '', '', '', '')]
12:34:17 [Plugins] Processing        : INTRSPD
12:34:17 [Plugins] Existing objects from Plugins_Objects: 7
12:34:17 [Plugins] Logged events from the plugin run    : 1
12:34:17 [Plugins] pluginEvents      count: 1
12:34:17 [Plugins] pluginObjects     count: 8
12:34:17 [Plugins] events_to_insert  count: 0
12:34:17 [Plugins] history_to_insert count: 8
12:34:17 [Plugins] objects_to_insert count: 1
12:34:17 [Plugins] objects_to_update count: 7

**Comment by jokob-sk** [comment] 2024-10-20 10:41
Thanks a lot - I think I've found the issue. I had a maximum value of 100 for the threshold for the DL/UL speed columns so if the value to be displayed went over 100, it didn't know what to do. This screenshot gave me the hint:

![image](https://github.com/user-attachments/assets/80b21da3-791f-456a-b32f-1070b4c14b86)


This should be available in the next release. It would be great if you could test this. Can you please switch to the `netalertx-dev` docker image (backup everything at first), in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

Thanks in advance,
j

**Comment by Stationary-1** [comment] 2024-10-20 10:43
DSL too fast?

**Comment by jokob-sk** [comment] 2024-10-20 10:43
> DSL too fast?

lol, yes

**Comment by Stationary-1** [comment] 2024-10-20 10:54
We were lucky...that speedtest ran once while my son was heavily drawing bandwidth on the guest net, that depressed the main net bandwidth... anyway the speed is poor for a 250 Mbit/s connection which we are supposed to have... 
I'll try your next commit as soon as available and report back.

**Comment by Stationary-1** [comment] 2024-10-20 10:58
Perfect:
![image](https://github.com/user-attachments/assets/52500784-a06a-492f-a4a2-161df009b9d2)

Thank you very much for you effort!!!

**Comment by jokob-sk** [comment] 2024-10-20 10:59
Thanks for helping me to get to the bottom of this :)

**Comment by Stationary-1** [comment] 2024-10-20 11:03
That was in my own interest. :-)

**Comment by jokob-sk** [comment] 2024-10-20 11:06
Let's see maybe something comes up :) thanks for the help 😉

**Comment by Stationary-1** [comment] 2024-10-28 07:52
@jokob-sk I have another short question regarding the behaviour of the schedule. The Pi has the correct system time, even after the end if daylight saving time (it automatically changed). The cron schedule 0 */4 * * * simply keeps running every four hours and did not get adapted to the actual time; is that a normal behaviour of cron that where before it ran the speedtest at 0, 4, 8, 12 hrs, now it runs at 23, 3, 7, 11?
![IMG_5995](https://github.com/user-attachments/assets/970d82e5-f111-4266-98f4-108210651319)

**Comment by jokob-sk** [comment] 2024-10-28 08:00
Hi @Stationary-1, according to chatgpt its expected. Please note that I have not tested this: 

Yes, this is expected behavior for cron. When daylight saving time changes, cron does not adjust the schedule to keep specific times aligned with the wall clock time; instead, it keeps intervals consistent based on system time. In your example, 0 */4 * * * will always run every four hours, but after the DST shift, the absolute times may move by an hour (such as from 0, 4, 8, etc., to 23, 3, 7, etc.).

This happens because cron schedules are based on intervals rather than specific fixed times. If you need it to run at specific times of the day regardless of DST shifts, you may need to explicitly schedule each time:

`0 0,4,8,12 * * *`

This schedule ensures it runs at midnight, 4 a.m., 8 a.m., and noon in local time, adjusting automatically with DST changes.

**Comment by Stationary-1** [comment] 2024-10-28 08:17
O.k. Thanks a lot for the e explanation! I have to learn how to use chatGPT as well, so I do not ask stupid questions😁 Basically cron goes strictly for UTC + Timezone at the moment of starting it. Afterwards it does not adapt anymore.
I might try the specific hours definition when I am back home from work.

**Comment by jokob-sk** [comment] 2024-10-28 08:19
All questions are good ones, I learn stuff this way too 🙂

**Comment by jokob-sk** [comment] 2024-10-31 04:56
releasing in 15 min -> closing

**Closed by jokob-sk** 2024-10-31 04:56 UTC
Labels: bug 🐛, next release/in dev image🚀
