### ISSUE TITLE
No settings are saved through ui and app.conf is not generated.

### ISSUE THREAD

**Issue by StinkyTACO** [jokob-sk/NetAlertX#712] opened 2024-06-22 01:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

app.conf does not generate and every restart of the container loses all setting previously changed.

### Expected Behavior

app.conf is generated and used so settings changed in the ui are saved

### Steps To Reproduce

just start the container with the docker guide settings.

### What branch are you running?

Production

### app.log

[app.log](https://github.com/user-attachments/files/15934745/app.log)
<img width="936" alt="Screenshot 2024-06-22 035524" src="https://github.com/jokob-sk/NetAlertX/assets/35038928/093c99d5-e158-49d7-a77b-799c822a35f9">

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment] 2024-06-22 06:20
Hi @StinkyTACO ,

I think this is a duplicate, please check this thread and report back if following the steps to clear the cache didn't help" https://github.com/jokob-sk/NetAlertX/issues/698

**Comment by Haegar333** [comment] 2024-06-22 20:55
I think I have the same error.
Running on unraid, I updated the docker container to the last update.

After restart, the config and db directory are empty, inside the docker and the attached directories on the host

I had a few reboots the last weeks without loosing settings, so this is new.

**Comment by jokob-sk** [comment] 2024-06-23 00:04
Hi @Haegar333 ,

Did you try to clear the cache as suggested here? 

https://github.com/jokob-sk/NetAlertX/issues/698

The next version will have better cache busting, so hopefully this won't happen in the future anymore

**Comment by jokob-sk** [comment] 2024-06-23 00:07
You can also test the `netalertx-dev` docker image if the issue occurs there. 

It would be great if you could test this (backup everything first or use a new container) on your end by switching to the above image and letting me know if the issue was resolved.

Thanks in advance,
j

**Comment by StinkyTACO** [comment] 2024-06-23 02:29
I have never used netalert before this is a fresh install with the latest image. hitting that refresh button does not create the app.conf file.

**Comment by StinkyTACO** [comment] 2024-06-23 02:30
i will try the dev image but something else must be wrong no ?

**Comment by StinkyTACO** [comment] 2024-06-23 02:35
the dev image does not create the app.conf either

**Comment by jokob-sk** [comment] 2024-06-23 04:28
hi @StinkyTACO ,

Make sure your permissions are set correctly: https://github.com/jokob-sk/NetAlertX/blob/main/docs/FILE_PERMISSIONS.md

**Comment by StinkyTACO** [comment] 2024-06-23 04:58
<img width="275" alt="image" src="https://github.com/jokob-sk/NetAlertX/assets/35038928/45eb0b7a-df1e-4d45-8ba1-29e574e97e93">

**Comment by StinkyTACO** [comment] 2024-06-23 04:58
no change in behaviour.

**Comment by jokob-sk** [comment] 2024-06-23 06:28
Can you try to run the container without mounting any volumes? e.g.:
```
docker run -d --rm --network=host \
  -e TZ=Europe/Berlin \
  -e PORT=20211 \
  jokobsk/netalertx:latest

```

**Comment by StinkyTACO** [comment] 2024-06-23 07:46
that works but only untill pulling the image again

**Comment by StinkyTACO** [comment] 2024-06-23 07:48
which if that is the case it would lose the config everytime there is an update

**Comment by StinkyTACO** [comment] 2024-06-23 07:54
i have also tried runnig the container with volumes instead of binds and with volumes it does't create the app.conf either.

**Comment by jokob-sk** [comment] 2024-06-23 08:25
> that works but only untill pulling the image again

That means that your permissions might be the issue. Could you please post your docker compose or run command?

**Comment by Haegar333** [comment] 2024-06-23 10:38
I checked the logs again, this is while startup:
![image](https://github.com/jokob-sk/NetAlertX/assets/80135668/b5db9eb9-0a53-4537-a643-a2bfffb997bd)

Still no config or db file in the directoris

**Comment by Haegar333** [comment] 2024-06-23 10:40
And:
![image](https://github.com/jokob-sk/NetAlertX/assets/80135668/c21cd808-5b1e-45f7-be7f-cbe4299223aa)

These are my volumes. Are that paths right (f.e. /home/pi/pialert/config)?

**Comment by jokob-sk** [comment] 2024-06-23 10:42
@Haegar333 

Seems like you are still mapping the olde folders. Did you follow the migration guide? https://github.com/jokob-sk/NetAlertX/blob/main/docs/MIGRATION.md

Please read it carefully in case you need to copy the old config or DB files.

**Comment by Haegar333** [comment] 2024-06-23 10:58
That's it!

I'm sorry to cause you trouble. 

But part of the problem is, that I relied on the unraid-app delivered settings that are obviously obsolete.

Anyway, my volume directories ave the cfg and db now.

**Comment by jokob-sk** [comment] 2024-06-23 12:24
@Haegar333 all good, glad it's resolved :)

**Comment by StinkyTACO** [comment] 2024-06-23 13:53
interesting because you asked for my command i decided to make a compose file with the same settings and now the app.conf is generated.

**Comment by StinkyTACO** [comment] 2024-06-23 13:54
previously i created the container with portainer through the ui with the exact same settings so this must be related to portainer.

**Comment by jokob-sk** [comment] 2024-06-23 21:54
@StinkyTACO Glad to hear that 👍. I assume this is resolved then. Closing and will reopen if needed.

**Closed by jokob-sk** 2024-06-23 21:55 UTC
Labels: bug 🐛, Waiting for reply⏳

**Comment by StinkyTACO** [comment] 2024-06-23 22:23
yes ive been using portainer for over 4 years now never had something like this happen before im both confused and intrigued.
