### ISSUE TITLE
Question: What do the colours in the presence graph mean? 

### ISSUE THREAD

**Issue by zodac** [jokob-sk/NetAlertX#751] opened 2024-07-29 20:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Am I willing to test this? 🧪

- [X] I will do my best to test this feature on the `netlertx-dev` image when requested within 48h and report bugs to help deliver a great user experience for everyone and not to break existing installations.

### Can I help implement this? 👩‍💻👨‍💻

- [ ] Yes
- [X] No

### Is your feature request related to a problem? Please describe

Hey, sorry for the simple question, but I didn't see a legend on the Maintenance> Presence page, or anything in the docs. What do the different colours (orange, green, blue) signify and which plugin is used to determine that status?

Thanks! 

### Describe the solution you'd like

An explanation of the colours on the presence graph, ideally as a legend/tooltip in the page. 

### Describe alternatives you've considered

A description in the docs.

### Anything else?

Nope. :)

**Comment by jokob-sk** [comment] 2024-07-29 22:54
Hi @zodac ,

This is an older part of the app, so I'm not 100% sure, but I think:

- blue - inactive sessions
- green - active sessions
- orange - inactive sessions that don't have a matched start/end time - I think this can be caused by application restarts, out-of-sync scans etc.

**Comment by jokob-sk** [comment] 2024-08-03 11:36
Answered -> Closing for now

**Closed by jokob-sk** 2024-08-03 11:36 UTC
Labels: Feature request➕
