### ISSUE TITLE
Icons missing for Raspberry Pi 5 devices

### ISSUE THREAD

**Issue by benbaker76** [jokob-sk/NetAlertX#892] opened 2024-11-22 23:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### The issue occurs in the following browsers. Select at least 2.

- [ ] Firefox
- [ ] Chrome
- [ ] Edge
- [ ] Safari (unsupported) - PRs welcome
- [ ] N/A - This is an issue with the backend

### Current Behavior

It's not showing all icons

### Expected Behavior

It should show all icons

### Steps To Reproduce

It doesn't seem to detect Raspberry Pi 5 devices on my network

![Screenshot from 2024-11-22 15-15-19](https://github.com/user-attachments/assets/8d352b3d-efbf-477e-b8fd-8e40ef49041d)

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment] 2024-11-23 01:20
Hi,

I set up a clean container on my end and the one Raspberry PI 4 I have was correctly assigned the right icon. 

![image](https://github.com/user-attachments/assets/9b9f3559-ec03-476b-9cb9-bdd5c0c4e187)

The icons are only set when a new device is discovered. 

The code can be found here:

https://github.com/jokob-sk/NetAlertX/blob/8f573cb41a03bde86d39b2860ddac90cb12c5980/server/device.py#L655

I don't see anything wrong with the logic, but I might be missing something.

**Comment by jokob-sk** [comment] 2024-11-23 01:23
One more thing - the VNDRPDT plugin is running on a schedule so if the vendor is missing during discovery and later is updated and re-discovered then this won't re-apply an icon. 

Not sure if this is happening.

**Comment by benbaker76** [comment] 2024-11-23 03:58
> One more thing - the VNDRPDT plugin is running on a schedule so if the vendor is missing during discovery and later is updated and re-discovered then this won't re-apply an icon.
> 
> Not sure if this is happening.

Yeah these devices were `(Unknown)` until the VNDRPDT plugin updated the vendor list. Any chance this could be updated so that icons can be refreshed when a new vendor is discovered?

**Comment by jokob-sk** [comment] 2024-11-23 20:27
Currently users can define a default icon when the device is discovered. See the NEWDEV_devIcon fir details. I would have to remove that functionality and keep the icon empty so that I know which device icons can be overwritten. Let me know if you think removing this functionality is worth it.

An alternative you can try is to set the VNDRPDT plugin to run once - this should make sure it updates before the app starts and every time the container restarts or settings are saved.

**Comment by benbaker76** [comment] 2024-12-01 00:59
> Currently users can define a default icon when the device is discovered. See the NEWDEV_devIcon fir details. I would have to remove that functionality and keep the icon empty so that I know which device icons can be overwritten. Let me know if you think removing this functionality is worth it.

I'm not sure why you'd have to remove that functionality? I think there should be default icons (which can also be defined by the user) and then vendor icons which will override those, and finally custom icons that can be assigned per-device.

> An alternative you can try is to set the VNDRPDT plugin to run once - this should make sure it updates before the app starts and every time the container restarts or settings are saved.

I don't think this should be required to get the appropriate icons to show. If you just give icons priorities custom > vendor > default it should be fine. You might need to add an `IconType` to the database to know which is currently assigned?

**Comment by jokob-sk** [comment] 2024-12-01 01:39
Thanks @benbaker76 for the reply!
 
>    Currently users can define a default icon when the device is discovered. See the NEWDEV_devIcon fir details. I would have to remove that functionality and keep the icon empty so that I know which device icons can be overwritten. Let me know if you think removing this functionality is worth it.

> I'm not sure why you'd have to remove that functionality? I think there should be default icons (which can also be defined by the user) and then vendor icons which will override those, and finally custom icons that can be assigned per-device.

The issue is how should I determine that an icon is allowed to be overwritten? Let's say this scenario:

Current app flow (most code here):

https://github.com/jokob-sk/NetAlertX/blob/d2ad35628fa225ef9431b91d314385c6b49fdfe0/server/device.py#L453

1. Scan gets executed
2. New device is found and defaults are initialized (e.g. NEWDEV_devIcon = `laptop`) as vendor and icon are not found
3. At a later stage, let's say the VENDOR DB gets updated
4. How do I determine that the `laptop` icon should be overwritten on which devices? Maybe users want to keep 3 devices with that icon of the same manufacturer, but have 2 changed? Maybe they used the laptop icon on multiple different devices. 

Maybe I'm overthinking it, just my brain is in a locked state now 🥲

**Comment by benbaker76** [comment] 2024-12-01 02:08
> The issue is how should I determine that an icon is allowed to be overwritten? Let's say this scenario:

How about add a setting to the VNDRPDT plugin called something like `Overwrite Icons` that can be off by default?

**Comment by jokob-sk** [comment] 2024-12-01 22:30
Hummm, good idea:

![image](https://github.com/user-attachments/assets/09a9a6cf-04de-4078-85ed-5aea3beda9ce)

https://github.com/jokob-sk/NetAlertX/commit/826bd8f524f8b80c54228ae30a6ad56d7a084846

this should do the trick. Would be good if you could test this.

**Comment by benbaker76** [comment] 2024-12-02 05:24
I enabled the setting and ran VNDRPDT but it doesn't seem to have updated any of the icons.

**Comment by jokob-sk** [comment] 2024-12-05 20:48
Hey @benbaker76 ,

I just tested this and it seems to be working on my instance:

Before setting the default icon to be overwritten:

![Screenshot at 21-10-26](https://github.com/user-attachments/assets/3b7e37e6-db5b-4002-9c09-255648aaa2e6)

After:

![Screenshot at 07-40-23](https://github.com/user-attachments/assets/a1dea7ac-cd37-4cc9-9f21-5cc27e2cf692)

I also pushed a name check just now, so if the name of the device contains `raspberry` it will get assigned. 

Could you please double check:

1. The default icon is matching on in teh NEWDEV_devIcon and on the devices you want updated?
2. You have the `NEWDEV_replace_preset_icon` checked
3. You can also enable debug and I added a debug print (search for `[Update Devices] recordsToUpdate` after you enable LOG_LEVEL debug): https://github.com/jokob-sk/NetAlertX/commit/80e8cb3f74211191338993cde00f0ea75a1cb646#diff-975b8ec678da22b97213a13eb1cd09839458245ce1f56b0fff729b4fdd1cbbf9R476


You can also double check my code, but I don't see any issue 🤔: https://github.com/jokob-sk/NetAlertX/blob/80e8cb3f74211191338993cde00f0ea75a1cb646/server/device.py#L667

Also, this update is happening during a scan, not when `VNDRPDT` is running.

**Comment by jokob-sk** [comment] 2024-12-22 23:49
Releasing -> Closing

**Closed by jokob-sk** 2024-12-22 23:49 UTC
Labels: Feature request➕, Waiting for reply⏳, next release/in dev image🚀
