### ISSUE TITLE
Grouping-devices-by-Vlans [setup] + Location dropdown missing custom values [bug]

### ISSUE THREAD

**Issue by kim3636** [jokob-sk/NetAlertX#862] opened 2024-10-24 10:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

I have alot of vlans in the network, so about 3100 devices, from all different vlans. These devices were discovered by SNMP, it's so messy and no clear, which devices belongs to chich vlan. SO i need a more user-friendly interface. that s easy to read. 

### Expected Behavior

I want to have a clear view of the devices ( they are about 3100 devices) from all different vlans. I want to group them by vlan, for example having a table of vlans, and when we click on vlan x we see the devices in that vlan. Or maybe the table will be sorted by vlans, so we see the vlan x column and then besides that the other columns of it's devices and their informations ( ip adresses , mac addresses, state ....)

### What branch are you running?

Production

### app.log

![image (4) (1)](https://github.com/user-attachments/assets/1ccc2b2a-69fc-47e3-bca7-39147f41e6be)

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment] 2024-10-24 11:15
Hi @kim3636 

You can use Location or Group fields to group devices under different VLANS:

![image](https://github.com/user-attachments/assets/8cc7272f-7120-4f7b-a96d-71daff182c75)

To speed this up you can also use the multi-rename functionality:

https://github.com/jokob-sk/NetAlertX/blob/main/docs/DEVICES_BULK_EDITING.md

Assigning devices to a VLAN is not as easy because not all services/plugins provide that information. 

Hope that makes sense.

**Comment by kim3636** [comment] 2024-10-24 12:03
okey thanks alot !

**Comment by kim3636** [comment] 2024-10-24 12:28
hello again, 
how can i add a new group or new location ?

**Comment by johnwang16** [comment] 2024-10-24 15:05
Edit an existing device and type in the name of the new group/location, click save. It'll be available for other devices after that.

**Comment by kim3636** [comment] 2024-10-24 15:24
> Edit an existing device and type in the name of the new group/location, click save. It'll be available for other devices after that.

Thank you !!

**Comment by LaurentAtJoes** [comment] 2024-10-26 14:22
> Edit an existing device and type in the name of the new group/location, click save. It'll be available for other devices after that.

Hi, this doesn't work for me : if I add a custom value to Location, it won't become available in the drop-down list for other devices.

Fresh install on docker (portainer) from today using latest.
I cleared cache, refreshed everything, even restarted the container.

Any idea ?

**Comment by jokob-sk** [comment] 2024-10-27 00:16
Hi @LaurentAtJoes ,

Did you refresh the page once you saved the device? I seems to work for me (tested in FF):

![image](https://github.com/user-attachments/assets/e9dcd9a4-ec99-4bc6-830e-c78a17c20250)

**Comment by LaurentAtJoes** [comment] 2024-10-27 17:38
Yes, several times (Shift+refresh in the browser, plus refresh button in NetAlert UI. FF here too)

Just to be on the same page : your screenshot shows "Group", but this does work. It's only "Location" that won't memorise custom values in the drop-down list.

**Comment by jokob-sk** [comment] 2024-10-27 20:59
Thanks @LaurentAtJoes , you are right. Missed the part that the issue is Location specific. 

![image](https://github.com/user-attachments/assets/e9e8bac4-92c5-4342-bd86-fa6f465b6bc7)

This should be available in the next release. It would be great if you could test this. Can you please switch to the `netalertx-dev` docker image (backup everything at first), in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now?

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

Thanks in advance,
j

**Comment by LaurentAtJoes** [comment] 2024-10-27 22:40
Yup, I confirm that with the dev image, Location shows the custom values in the drop-down list. 👍

**Comment by jokob-sk** [comment] 2024-10-31 04:55
releasing in 15 min -> closing

**Closed by jokob-sk** 2024-10-31 04:55 UTC
Labels: Feature request➕, Waiting for reply⏳, next release/in dev image🚀
